//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendanceView
    {
        public int AttendanceId { get; set; }
        public int AttendanceStudentId { get; set; }
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public bool IsPresent { get; set; }
    }
}
