//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public int AttendanceId { get; set; }
        public int AttendanceStudentId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public bool IsPresent { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual StudentInformation StudentInformation { get; set; }
    }
}
